### ISSUE TITLE
Unable to integrate with express inversify-express-utils

### ISSUE THREAD

**Issue by Halynsky** [jackypan1989/express-query-parser#2]
Thx for library man.

I have an issue with integration into inversify stack

**Code**
```
import queryParser from 'express-query-parser'

    ...
    inversifyExpressServer.setConfig(async (app: express.Application) => {
        ...
        app.use(
            queryParser({
                parseNull: true,
                parseBoolean: true
            })
        )
    });

```

**Error**
```
[2020-11-17T15:51:48.899] [ERROR] main - TypeError: express_query_parser_1.default is not a function
    at ...\backend\typescript\src\App.ts:110:28
    at InversifyExpressServer.build ...\backend\node_modules\inversify-express-utils\lib\server.js:119:28)
    at ...\typescript\src\App.ts:127:41
    at processTicksAndRejections (internal/process/task_queues.js:97:5) (<anonymous> ..\App.ts:99:27)
```

**P.S.**
1. Add github link to npm description plz
2. Add documentation line about ramda package requirement

**Comment by jackypan1989** [comment]
I will dig this soon (maybe this weekend). 
Or you can make some PR to do this.

**Comment by jackypan1989** [comment]
@Halynsky 

```
import queryParser from 'express-query-parser'
```

should be 

```
import { queryParser } from 'express-query-parser'
```
